apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: demo
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: public.ecr.aws/q2y7e9r0/frontenduri:latest
        imagePullPolicy: Always
        # env:
        #   - name: backendUrl
        #     value: "http://demo.thevy.xyz/api/ge" 
        ports:
        - containerPort: 3000