apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: demo
  labels: 
    role: backend
    env: demo
spec: 
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector: 
    matchLabels:
      role: backend
  template:
    metadata:
      labels:
        role: backend
    spec:
      containers:
      - name: backend
        image: vivekcode101/pkmb:latest
        imagePullPolicy: Always
