on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to Release'
        required: true
        type: string
permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout
      
jobs:
  image-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build  image
        run: |
          docker build -t ${{ inputs.image }}:${{ inputs.tag }} -f custom-fe-be/${{ inputs.image }}/dockerfile .
          docker tag ${{ inputs.image }}:${{ inputs.tag }} public.ecr.aws/${{ secrets.alias }}/${{ inputs.image }}:${{ inputs.tag }}

      - name: Tag and push Docker image to Docker Hub
        run: |
          docker push public.ecr.aws/${{ secrets.alias }}/${{ inputs.image }}:${{ inputs.tag }}

      - uses: sigstore/cosign-installer@11086d25041f77fe8fe7b9ea4e48e3b9192b8f19 # v3.1.2
      - name: Sign the images
        run: |
          cosign sign \
            --yes  public.ecr.aws/${{ secrets.alias }}/${{ inputs.image }}:${{ inputs.tag }}
